### ISSUE TITLE
Change phpunit package version

### ISSUE THREAD

**Issue by papac** [bowphp/policier#1]
The unity test fail because phpunit version not support the setting php version in travis.

**Comment by peter279k** [comment]
Here are the PHP versions requirement for PHPUnit.

- The PHPUnit `7.x` requires `php-7.1` at least.
- The PHPUnit `8.x` requires `php-7.2` at least.

And it seems that this package requires `php-7.1` at least and it should define PHPUnit `^7.0` version in `composer.json`.

**Comment by peter279k** [comment]
The references are about `PHPUnit` versions are for PHP version requirements.

- [PHPUnit 8.x](https://phpunit.de/getting-started/phpunit-7.html)
- [PHPUnit 7.x](https://phpunit.de/getting-started/phpunit-8.html)

**Comment by papac** [comment]
@peter279k actualy it's the version ^7.0 of PHPunit who is define.

Thank you for your better precision.
