### ISSUE TITLE
Change minimum stability to stable 

### ISSUE THREAD

**Issue by peter279k** [bowphp/policier#2]
As title, the `minimum-stability` defines the `dev` in `composer.json` and this will tell `composer` to install the development package version.

I think we should change into `stable` because nobody want to install a development package on their web applications/services.

**Comment by papac** [comment]
Ok thank you @peter279k. Can You fixed it and make a PR.

**Comment by peter279k** [comment]
@papac, I will create related PR to solve this issue at my available time :).

Thank you for your concern again.
